# ip of the affected host
string host

# identifier of the affected node
string node

# action  [restart, stop, command]
string action

# command-line arguments (for action command)
string[] args
---
# message returned upon completion
string returnmessage